### ISSUE TITLE
Costume reverts after Marrow Brooch animation ends

### ISSUE THREAD

**Issue by piecemealcranky** [hugedong69/arborean-apparel#2]
Hello! I've been trying AA for a bit but I noticed if I pop the Marrow Brooch and the black flame/silhouette graphic ends with the brooch, the costume I customized with AA gets reverted. If I go through a loading screen I could see my AA costume again.

**Comment by hugedong69** [comment]
Fixed maybe, lemme kno

**Comment by piecemealcranky** [comment]
As of v 0.55, the issue persists. It does still revert back to AA customization when you port or change channels.

**Comment by hugedong69** [comment]
If you don't have the UNICAST opcode that is asked for it wont work, make sure you have it and lemme kno if you do

**Comment by piecemealcranky** [comment]
I don't think I have this opcode then. A search on Discord gave me something like months ago. O.O

**Comment by hugedong69** [comment]
I pushed it to https://github.com/meishuu/tera-data so if you could download and overwrite the existing tera-data with that in your tera-proxy/node_modules directory and get back to me, that'd be niceu

**Comment by piecemealcranky** [comment]
Much appreciated, will report back in a jiffy!

**Comment by piecemealcranky** [comment]
Hm, still doesn't work with latest tera-data and AA. I might be doing something wrong then xd

**Comment by hugedong69** [comment]
Should be fixed now, reopen if not
